# Generated by Django 5.2.10 on 2026-01-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professionals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="professional",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Professional",
                "verbose_name_plural": "Professionals",
            },
        ),
        migrations.AddField(
            model_name="professional",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="professional",
            name="company_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="professional",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="professional",
            name="full_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="professional",
            name="source",
            field=models.CharField(
                choices=[
                    ("direct", "Direct"),
                    ("partner", "Partner"),
                    ("internal", "Internal"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="professional",
            index=models.Index(
                fields=["source", "created_at"], name="idx_source_created"
            ),
        ),
        migrations.AddIndex(
            model_name="professional",
            index=models.Index(
                fields=["company_name", "source"], name="idx_company_source"
            ),
        ),
        migrations.AlterModelTable(
            name="professional",
            table="professionals",
        ),
    ]
